"""Дефолты для env и подсказок в UI — одна точка, без «магических» чисел в handlers/README."""

# --- RATE_LIMIT_SECONDS ---
RATE_LIMIT_SECONDS_DEFAULT = 3600
RATE_LIMIT_SECONDS_MIN = 10
RATE_LIMIT_SECONDS_MAX = 604800

# --- DISCUSSION_SNIPPET_MAX_CHARS ---
DISCUSSION_SNIPPET_MAX_CHARS_DEFAULT = 2500
DISCUSSION_SNIPPET_MAX_CHARS_MIN = 200
DISCUSSION_SNIPPET_MAX_CHARS_MAX = 8000

# --- IMAGE_MAX_SIDE ---
IMAGE_MAX_SIDE_DEFAULT = 900
IMAGE_MAX_SIDE_MIN = 64
IMAGE_MAX_SIDE_MAX = 4096

# Лимит чтения исходника, если IMAGE_VALIDATION_ENABLED=0 (нет ImageSafetyConfig)
IMAGE_MAX_SOURCE_BYTES_NO_SAFETY = 25 * 1024 * 1024

# --- LOCAL_LLM_MAX_OUTPUT_CHARS (и SQLite seed в Storage) ---
LOCAL_LLM_MAX_OUTPUT_CHARS_DEFAULT = 2400
LOCAL_LLM_MAX_OUTPUT_CHARS_MIN = 200
LOCAL_LLM_MAX_OUTPUT_CHARS_MAX = 8000

# --- IMAGE_MAX_FILE_BYTES (Sightengine / Pillow gate) ---
IMAGE_MAX_FILE_BYTES_DEFAULT = 20 * 1024 * 1024
IMAGE_MAX_FILE_BYTES_MIN = 4096
IMAGE_MAX_FILE_BYTES_MAX = 80 * 1024 * 1024

# --- IMAGE_MAX_WIDTH / HEIGHT ---
IMAGE_MAX_WIDTH_DEFAULT = 8192
IMAGE_MAX_HEIGHT_DEFAULT = 8192
IMAGE_MAX_DIMENSION_MIN = 64
IMAGE_MAX_DIMENSION_MAX = 32000
